# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314d9070dc95a83eb8f09fa0cae59b47f0a8c163995bd12434ffcff09a6257ba177c28ad109666f3d6107bcf018e9a38cda272e3af106f85b84183d4f75c1c55

test:
  secret_key_base: 6d23c9ab7877b6dce3d54bc80bc76f307bf511e3a43753b6e622a4c94ee6c0c1f422050266bdfc083120d42a3b02ee8dbd386141da7646ea0781e24da8e73150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
